const HERO_FEED='https://cdn.jsdelivr.net/gh/warungerik/MLBB-Hero-Scraper@main/mlbb_heroes.json';
const ROLE_TABS=['All','Tank','Marksman','Fighter','Assassin','Mage','Support'];
const LANES=['EXP','JUNGLE','MID','GOLD','ROAM'];
const TOURNAMENT_STEPS=[
 ['Blue','ban',1],['Red','ban',1],['Blue','ban',2],['Red','ban',2],
 ['Blue','pick',1],['Red','pick',1],['Red','pick',2],['Blue','pick',2],['Blue','pick',3],['Red','pick',3],
 ['Blue','ban',3],['Red','ban',3],
 ['Red','pick',4],['Blue','pick',4],['Blue','pick',5],['Red','pick',5]
].map((x,i)=>({side:x[0],type:x[1],slot:x[2],index:i}));
const RANKED_PICK_STEPS=[
 ['Blue','pick',1],['Red','pick',1],['Red','pick',2],['Blue','pick',2],['Blue','pick',3],['Red','pick',3],['Red','pick',4],['Blue','pick',4],['Blue','pick',5],['Red','pick',5]
].map((x,i)=>({side:x[0],type:x[1],slot:x[2],index:i}));
const TAG_HINTS={
 Fanny:{good:['immobile','backline'],bad:['hard_cc','anti_dash']},Ling:{good:['immobile','backline'],bad:['hard_cc','anti_dash']},Nolan:{good:['squishy','immobile'],bad:['hard_cc','peel']},Hirara:{good:['squishy','backline'],bad:['hard_cc','peel']},Masha:{good:['backline','single_target'],bad:['kite','sustain']},Atlas:{good:['grouped','immobile'],bad:['purify','disengage']},Minotaur:{good:['dive','grouped'],bad:['poke','disengage']},Diggie:{good:['hard_cc','engage'],bad:['burst','pickoff']},Valir:{good:['dive','melee'],bad:['long_range','burst']},Khufra:{good:['dash','assassin'],bad:['poke','disengage']},Karrie:{good:['tank','frontline'],bad:['burst','dive']},Claude:{good:['frontline','grouped'],bad:['hard_cc','burst']},Bruno:{good:['squishy','frontline'],bad:['dive','hard_cc']},Lylia:{good:['melee','grouped'],bad:['long_range','pickoff']},Novaria:{good:['slow','immobile'],bad:['dive','assassin']},Carmilla:{good:['grouped','frontline'],bad:['disengage','range']},Barats:{good:['burst','assassin'],bad:['tank_shred','kite']},Belerick:{good:['marksman','attack_speed'],bad:['true_damage','poke']},Gloo:{good:['melee','immobile'],bad:['purify','burst']},Aulus:{good:['frontline','extended_fight'],bad:['kite','burst']},Obsidia:{good:['frontline','extended_fight'],bad:['dive','hard_cc']}
};
let heroes=[];
let aiTimer=null;
let state={mode:'tournament',scope:'Combined',filter:'All',search:'',userSide:'',sideDraft:'Blue',started:false,actions:[],rankedBans:[],rankedBanTarget:5};

function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]))}
function clamp(v){return Math.max(0,Math.min(100,v))}
function toast(msg){const el=document.getElementById('toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),1700)}
function persist(){localStorage.setItem('mlbb-new-coach-v3',JSON.stringify({mode:state.mode,scope:state.scope,userSide:state.userSide,actions:state.actions,rankedBans:state.rankedBans,rankedBanTarget:state.rankedBanTarget,started:state.started}))}
function restore(){try{const x=JSON.parse(localStorage.getItem('mlbb-new-coach-v3')||'{}');if(x.mode)state.mode=x.mode;if(x.scope)state.scope=x.scope;if(x.userSide)state.userSide=x.userSide;if(Array.isArray(x.actions))state.actions=x.actions;if(Array.isArray(x.rankedBans))state.rankedBans=x.rankedBans;if(x.rankedBanTarget)state.rankedBanTarget=x.rankedBanTarget;if(typeof x.started==='boolean')state.started=x.started}catch{}}
function steps(){return state.mode==='tournament'?TOURNAMENT_STEPS:RANKED_PICK_STEPS}
function currentStep(){return state.started?steps()[state.actions.length]||null:null}
function phaseText(){if(state.mode==='ranked'&&!state.started)return'RANKED • BAN SETUP';const i=state.actions.length;if(state.mode==='ranked')return i<6?'RANKED • FIRST PICK PHASE':'RANKED • FINAL PICK PHASE';if(i<4)return'TOURNAMENT • FIRST BAN PHASE';if(i<10)return'TOURNAMENT • FIRST PICK PHASE';if(i<12)return'TOURNAMENT • SECOND BAN PHASE';if(i<16)return'TOURNAMENT • SECOND PICK PHASE';return'DRAFT COMPLETE'}
function byName(n){return heroes.find(h=>h.name===n)}
function usedNames(){return new Set([...state.actions.map(a=>a.hero),...state.rankedBans])}
function picks(side){return state.actions.filter(a=>a.side===side&&a.type==='pick').map(a=>byName(a.hero)).filter(Boolean)}
function sideBans(side){return state.actions.filter(a=>a.side===side&&a.type==='ban').map(a=>byName(a.hero)).filter(Boolean)}
function lanes(h){return h?.lanes||[]}
function roles(h){return h?.roles||[]}
function openRoles(side){const covered=new Set(picks(side).flatMap(lanes));return LANES.filter(x=>!covered.has(x))}
function isAITurn(step=currentStep()){if(!step||!state.started)return false;if(state.userSide==='Spectator')return true;return step.side!==state.userSide}
function isUserTurn(step=currentStep()){return !!(step&&state.started&&state.userSide!=='Spectator'&&step.side===state.userSide)}
function isRankedBanSetup(){return state.mode==='ranked'&&!state.started}

function inferRoles(name,ls){const over=window.MLBB_ROSTER.roleOverrides[name];if(over)return over;const out=[];if(ls.includes('ROAM'))out.push('Tank','Support');if(ls.includes('GOLD'))out.push('Marksman');if(ls.includes('MID'))out.push('Mage');if(ls.includes('JUNGLE'))out.push('Assassin');if(ls.includes('EXP'))out.push('Fighter');return [...new Set(out)]}
function baseRoster(){const r=window.MLBB_ROSTER;return r.names.map((name,i)=>{const ls=Object.entries(r.lanes).filter(([,arr])=>arr.includes(name)).map(([lane])=>lane);return{id:'local'+i,name,lanes:ls,roles:inferRoles(name,ls),icon_url:''}})}
function mergeFeed(arr){const map=new Map(baseRoster().map(h=>[h.name.toLowerCase(),h]));for(const raw of arr||[]){const name=raw.name||raw.hero_name||raw.heroName;if(!name)continue;const key=name.toLowerCase(),existing=map.get(key)||{id:raw.id||key,name,lanes:[],roles:[],icon_url:''};const rls=Array.isArray(raw.roles)?raw.roles:(raw.role?[raw.role]:[]);const lns=Array.isArray(raw.lanes)?raw.lanes:(raw.lane?[raw.lane]:[]);map.set(key,{...existing,name,roles:rls.length?rls:existing.roles,lanes:lns.length?lns.map(x=>String(x).toUpperCase()):existing.lanes,icon_url:raw.icon_url||raw.icon||raw.imageUrl||raw.image_url||existing.icon_url})}return [...map.values()].sort((a,b)=>a.name.localeCompare(b.name))}

function metaEvidence(hero){const name=hero.name,m=window.MLBB_META;let score=50,confidence='Low',detail='No direct Week 6+ evidence in the bundled snapshot.';
 if(state.scope==='Combined'){
   if(m.recencyComposite[name]!=null){score=m.recencyComposite[name];confidence=score>=88?'High':'Medium';detail='Recency-weighted composite across MPL PH Week 6+, MPL ID Week 6+, and current Asian Games.'}
 }else if(state.scope==='MPL PH'){
   if(m.phWeek6Observed[name]!=null){score=m.phWeek6Observed[name];confidence='Medium';detail='Observed MPL PH Week 6+ priority signal. Exact aggregate counts are not invented.'}
 }else if(state.scope==='MPL ID'){
   const s=m.idSeason18[name];if(s){const p=s.pick+s.ban;score=clamp(Math.round(52+(p/109)*45+((s.wr??50)-50)*.12));confidence=p>=80?'High':p>=30?'Medium':'Low';detail=`Current S18 baseline: ${s.pick} picks, ${s.ban} bans${s.wr==null?'':`, ${s.wr}% WR`}. Week 6+ receives priority in the coach weighting.`}
 }else{
   const s=m.asianGames[name];if(s){if(s.pick!=null)score=clamp(Math.round(55+(s.pick/9)*38+(((s.wr??50)-50)*.1)));else score=s.signal||65;confidence=s.pick>=7?'High':'Medium';detail=s.pick!=null?`Asian Games main-event signal: ${s.pick} picks${s.wr==null?'':`, ${s.wr}% WR`}.`:'Observed in current Asian Games draft records.'}
 }
 return{score,confidence,detail}}
function tags(h){const rs=roles(h).join(' ').toLowerCase(),ls=lanes(h),t=new Set();if(/tank/.test(rs))['tank','frontline','hard_cc','engage'].forEach(x=>t.add(x));if(/support/.test(rs))['support','peel','disengage'].forEach(x=>t.add(x));if(/assassin/.test(rs))['assassin','dive','burst','dash'].forEach(x=>t.add(x));if(/marksman/.test(rs))['marksman','backline','sustained','tank_shred','squishy'].forEach(x=>t.add(x));if(/mage/.test(rs))['mage','magic','poke','burst','waveclear'].forEach(x=>t.add(x));if(/fighter/.test(rs))['fighter','frontline','sustain','melee'].forEach(x=>t.add(x));if(ls.includes('JUNGLE'))t.add('objective');if(ls.includes('ROAM'))t.add('engage');const hint=TAG_HINTS[h.name];if(hint){for(const g of hint.good||[])t.add('good_'+g);for(const b of hint.bad||[])t.add('bad_'+b)}return t}
function matchupValue(a,b){const A=tags(a),B=tags(b);let v=0;if(A.has('hard_cc')&&B.has('dash'))v+=3;if(A.has('peel')&&B.has('dive'))v+=2;if(A.has('tank_shred')&&B.has('frontline'))v+=3;if(A.has('poke')&&B.has('melee'))v+=2;if(A.has('dive')&&B.has('backline'))v+=2;if(A.has('sustain')&&B.has('burst'))v+=1;if(A.has('disengage')&&B.has('engage'))v+=2;if(A.has('burst')&&B.has('squishy'))v+=2;if(B.has('hard_cc')&&A.has('dash'))v-=3;if(B.has('tank_shred')&&A.has('frontline'))v-=2;if(B.has('dive')&&A.has('backline'))v-=2;const hint=TAG_HINTS[a.name];if(hint){for(const x of hint.good||[])if(B.has(x))v+=1.5;for(const x of hint.bad||[])if(B.has(x))v-=1.5}return v}
function counterScore(hero,step){const enemy=picks(step.side==='Blue'?'Red':'Blue');if(!enemy.length)return 50;const vals=enemy.map(e=>matchupValue(hero,e));return clamp(Math.round(50+Math.max(...vals)*8+(vals.reduce((a,b)=>a+b,0)/vals.length)*5))}
function synergyPair(a,b){const A=tags(a),B=tags(b);let s=0;if(A.has('engage')&&B.has('burst'))s+=2;if(B.has('engage')&&A.has('burst'))s+=2;if(A.has('peel')&&B.has('backline'))s+=2;if(B.has('peel')&&A.has('backline'))s+=2;if(A.has('frontline')&&B.has('marksman'))s+=1.5;if(B.has('frontline')&&A.has('marksman'))s+=1.5;if(A.has('magic')&&B.has('marksman'))s+=1;if(B.has('magic')&&A.has('marksman'))s+=1;return s}
function synergyScore(hero,side){const allies=picks(side);if(!allies.length)return 50;return clamp(Math.round(50+(allies.map(x=>synergyPair(hero,x)).reduce((a,b)=>a+b,0)/allies.length)*10))}
function roleFit(hero,step){if(step.type==='ban'){const enemy=step.side==='Blue'?'Red':'Blue';return lanes(hero).some(x=>openRoles(enemy).includes(x))?72:50}const need=openRoles(step.side);if(lanes(hero).some(x=>need.includes(x)))return 84;if(lanes(hero).length>1)return 65;return 38}
function compositionScore(hero,side){const team=[...picks(side),hero],ts=team.map(tags);let s=42;if(ts.some(t=>t.has('frontline')))s+=10;if(ts.some(t=>t.has('engage')))s+=8;if(ts.some(t=>t.has('peel')))s+=5;if(ts.some(t=>t.has('magic')))s+=6;if(ts.some(t=>t.has('marksman')))s+=6;if(ts.some(t=>t.has('objective')))s+=5;if(new Set(team.flatMap(lanes)).size>=Math.min(team.length,5))s+=8;return clamp(s)}
function denialScore(hero,step){const enemy=step.side==='Blue'?'Red':'Blue';let s=45;if(lanes(hero).some(x=>openRoles(enemy).includes(x)))s+=17;s+=(metaEvidence(hero).score-50)*.55;if(lanes(hero).length>1)s+=7;return clamp(Math.round(s))}
function coachAnalysis(hero,step){const meta=metaEvidence(hero),counter=counterScore(hero,step),role=roleFit(hero,step),syn=synergyScore(hero,step.side),comp=compositionScore(hero,step.side),denial=denialScore(hero,step),flex=clamp(45+Math.max(0,lanes(hero).length-1)*22);let score;
 if(step.type==='ban')score=Math.round(meta.score*.44+counter*.20+denial*.20+role*.08+flex*.08);else score=Math.round(meta.score*.38+counter*.19+role*.16+syn*.11+comp*.10+denial*.03+flex*.03);score=clamp(score);
 let type=step.type==='ban'?(counter>=70?'Direct Counter Ban':meta.score>=88?'Meta Ban':denial>=72?'Denial Ban':'Role Target Ban'):(counter>=72?'Counter Pick':syn>=70?'Synergy Pick':lanes(hero).length>1?'Flex Pick':meta.score>=88?'Meta Pick':'Pick');
 const reasons=[];if(meta.score>=75)reasons.push('high recent pro priority');if(counter>=65)reasons.push('strong into current enemy picks');if(role>=72&&step.type==='pick')reasons.push('fills an open role');if(syn>=65)reasons.push('strong ally synergy');if(comp>=65)reasons.push('improves composition');if(denial>=70)reasons.push('denial value');if(!reasons.length)reasons.push('best contextual balance');
 const enemy=picks(step.side==='Blue'?'Red':'Blue');const good=enemy.map(e=>({n:e.name,v:matchupValue(hero,e)})).filter(x=>x.v>0).sort((a,b)=>b.v-a.v).slice(0,3).map(x=>x.n);const threats=enemy.map(e=>({n:e.name,v:matchupValue(hero,e)})).filter(x=>x.v<0).sort((a,b)=>a.v-b.v).slice(0,3).map(x=>x.n);const allies=picks(step.side).map(e=>({n:e.name,v:synergyPair(hero,e)})).filter(x=>x.v>0).sort((a,b)=>b.v-a.v).slice(0,3).map(x=>x.n);
 return{score,type,reason:reasons.slice(0,3).join(' • '),meta,counter,role,syn,comp,denial,flex,good,threats,allies}}
function pseudoStep(){if(currentStep())return currentStep();return{side:state.userSide&&state.userSide!=='Spectator'?state.userSide:'Blue',type:isRankedBanSetup()?'ban':'pick',slot:0}}
function topRecommendations(limit=5){const step=pseudoStep();return heroes.filter(h=>!usedNames().has(h.name)).map(hero=>({hero,a:coachAnalysis(hero,step)})).sort((x,y)=>y.a.score-x.a.score||x.hero.name.localeCompare(y.hero.name)).slice(0,limit)}

function renderMode(){document.querySelectorAll('.mode-tab').forEach(b=>b.classList.toggle('active',b.dataset.mode===state.mode));document.getElementById('rankedSetup').classList.toggle('hidden',state.mode!=='ranked');document.getElementById('modePill').textContent='MODE: '+state.mode.toUpperCase();document.getElementById('rankedBanTarget').value=state.rankedBanTarget;document.getElementById('rankedBanCount').textContent=`${state.rankedBans.length} / ${state.rankedBanTarget} selected`}
function renderRoleTabs(){const root=document.getElementById('roleTabs');root.innerHTML='';for(const r of ROLE_TABS){const b=document.createElement('button');b.className='role-tab'+(state.filter===r?' active':'');b.textContent=r;b.onclick=()=>{state.filter=r;renderHeroGrid()};root.appendChild(b)}}
function cardRole(hero){return roles(hero).slice(0,2).join(' / ')||lanes(hero).slice(0,2).join(' / ')||'Hero'}
function heroMatches(h){const q=state.search.toLowerCase();return(!q||h.name.toLowerCase().includes(q))&&(state.filter==='All'||roles(h).some(r=>r.toLowerCase()===state.filter.toLowerCase()))}
function heroImg(hero,cls=''){return hero.icon_url?`<img class="${cls}" src="${esc(hero.icon_url)}" alt="${esc(hero.name)}" loading="lazy">`:esc(hero.name[0])}
function renderHeroGrid(){const root=document.getElementById('heroGrid'),recs=new Set(topRecommendations().map(x=>x.hero.name)),step=currentStep();root.innerHTML='';for(const h of heroes.filter(heroMatches)){const used=usedNames().has(h.name),pre=state.rankedBans.includes(h.name),analysis=coachAnalysis(h,pseudoStep());let disabled=false;if(!isRankedBanSetup())disabled=!isUserTurn(step);const el=document.createElement('div');el.className='hero-card'+(used&&!pre?' used':'')+(disabled?' disabled':'')+(recs.has(h.name)?' recommended':'')+(pre?' prebanned':'');el.innerHTML=`<div class="hero-face">${heroImg(h)}</div><div class="hero-name">${esc(h.name)}</div><div class="hero-role">${esc(cardRole(h))}</div><div class="hero-score">${analysis.score}</div>`;el.onclick=()=>handleHeroClick(h.name);el.ondblclick=()=>openHeroDrawer(h);root.appendChild(el)}document.getElementById('heroCountLabel').textContent=`${heroes.length} heroes loaded`}
function banToken(hero,global=false){return `<div class="ban-token${global?' global':''}" title="${hero?esc(hero.name):''}">${hero?heroImg(hero):'?'}</div>`}
function renderBans(){const blue=document.getElementById('blueBans'),red=document.getElementById('redBans');if(state.mode==='ranked'){const list=state.rankedBans.map(byName).filter(Boolean);const a=list.filter((_,i)=>i%2===0),b=list.filter((_,i)=>i%2===1);blue.innerHTML=a.map(h=>banToken(h,true)).join('');red.innerHTML=b.map(h=>banToken(h,true)).join('');return}const bb=sideBans('Blue'),rb=sideBans('Red');blue.innerHTML='';red.innerHTML='';for(let i=0;i<3;i++){blue.innerHTML+=banToken(bb[i]);red.innerHTML+=banToken(rb[i])}}
function renderPicks(){for(const side of['Blue','Red']){const root=document.getElementById(side.toLowerCase()+'Picks'),list=picks(side);root.innerHTML='';for(let i=0;i<5;i++){const h=list[i];const el=document.createElement('div');el.className='pick-slot'+(h?' filled':'');if(h)el.innerHTML=`<div class="hero-face" style="width:56px;height:56px;flex:none">${heroImg(h)}</div><div><div class="pick-name">${esc(h.name)}</div><div class="pick-role">${esc(lanes(h).join(' / ')||cardRole(h))}</div></div>`;else el.innerHTML=`<span class="placeholder">Pick ${i+1}</span>`;if(h)el.onclick=()=>openHeroDrawer(h);root.appendChild(el)}}}
function renderHeader(){document.getElementById('userSidePill').textContent='USER SIDE: '+(state.userSide||'NOT SET').toUpperCase();document.getElementById('metaPill').textContent='META: WEEK 6+ PRIORITY';document.getElementById('phaseLabel').textContent=phaseText();const step=currentStep();if(isRankedBanSetup()){document.getElementById('actionLabel').textContent=`Select ${state.rankedBanTarget} banned heroes`;document.getElementById('turnPill').textContent=state.rankedBans.length>=5?'READY WHEN COMPLETE':'MINIMUM 5';return}if(!state.started){document.getElementById('actionLabel').textContent='Choose your side';document.getElementById('turnPill').textContent='WAITING';return}if(!step){document.getElementById('actionLabel').textContent='Draft Complete';document.getElementById('turnPill').textContent='ANALYSIS READY';return}document.getElementById('actionLabel').textContent=`${step.side} ${step.type==='ban'?'Ban':'Pick'} ${step.slot}`;document.getElementById('turnPill').textContent=isAITurn(step)?'AI COACH TURN':'YOUR TURN'}
function renderRecommendations(){const root=document.getElementById('recommendations');root.innerHTML='';for(const{hero,a}of topRecommendations()){const el=document.createElement('div');el.className='rec';el.innerHTML=`<div class="rec-head"><div class="rec-face">${heroImg(hero)}</div><div><div class="rec-name">${esc(hero.name)}</div><div class="rec-score">Priority ${a.score}/100</div></div></div><span class="rec-type">${esc(a.type)}</span><div class="rec-reason">${esc(a.reason)}</div>`;el.onclick=()=>openHeroDrawer(hero);root.appendChild(el)}}
function renderIntel(){const root=document.getElementById('draftIntel'),step=pseudoStep(),enemy=step.side==='Blue'?'Red':'Blue',need=openRoles(step.side);const top=topRecommendations(1)[0];const conf=top?.a.meta.confidence||'Low';document.getElementById('confidenceBadge').textContent='Confidence: '+conf;const bannedNote=state.mode==='ranked'?`${state.rankedBans.length}/${state.rankedBanTarget} ranked bans locked`:`${sideBans('Blue').length+sideBans('Red').length}/6 tournament bans used`;root.innerHTML=`<div class="intel"><div class="intel-row"><b>RECENCY MODEL</b><span>MPL PH Week 6+, MPL ID Week 6+, and current Asian Games are prioritized over older season data.</span></div><div class="intel-row"><b>OPEN ROLES (${esc(step.side)})</b><span>${esc(need.join(', ')||'Role coverage complete')}</span></div><div class="intel-row"><b>ENEMY OPEN ROLES (${esc(enemy)})</b><span>${esc(openRoles(enemy).join(', ')||'Role coverage complete')}</span></div><div class="intel-row"><b>BAN STATE</b><span>${esc(bannedNote)}</span></div></div>`}
function renderMeta(){const root=document.getElementById('metaContent'),m=window.MLBB_META,rows=Object.entries(m.recencyComposite).sort((a,b)=>b[1]-a[1]).slice(0,30);root.innerHTML=`<p class="mode-note">${esc(m.methodology)}</p><table class="meta-table"><thead><tr><th>#</th><th>Hero</th><th>Recency Priority</th><th>MPL ID S18 baseline</th><th>Asian Games signal</th></tr></thead><tbody>${rows.map(([name,score],i)=>{const id=m.idSeason18[name],ag=m.asianGames[name];return`<tr><td>${i+1}</td><td><b>${esc(name)}</b></td><td class="meta-score">${score}</td><td>${id?`${id.pick}P / ${id.ban}B${id.wr==null?'':` / ${id.wr}% WR`}`:'—'}</td><td>${ag?(ag.pick!=null?`${ag.pick} picks${ag.wr==null?'':` / ${ag.wr}% WR`}`:'current-event signal'):'—'}</td></tr>`}).join('')}</tbody></table>`}
function renderDirectory(){const root=document.getElementById('heroDirectory');root.innerHTML='';for(const h of heroes){const el=document.createElement('div');el.className='hero-card';el.innerHTML=`<div class="hero-face">${heroImg(h)}</div><div class="hero-name">${esc(h.name)}</div><div class="hero-role">${esc(cardRole(h))}</div>`;el.onclick=()=>openHeroDrawer(h);root.appendChild(el)}document.getElementById('directoryCount').textContent=`${heroes.length} heroes`}
function renderSources(){const m=window.MLBB_META;document.getElementById('sourcesContent').innerHTML=`<div class="source-list">${m.sources.map(s=>`<div class="source-item"><b>${esc(s.name)} • ${esc(s.kind)}</b><p>${esc(s.note)}</p><p>${esc(s.url)}</p></div>`).join('')}<div class="source-item"><b>Integrity rule</b><p>Exact statistics are shown only where they are available in the bundled verified snapshot. Week 6+ priority scores are analytical composites and are not presented as official percentages.</p></div></div>`}
function assignRoles(side){const pool=picks(side).map(h=>({h,ls:lanes(h)})),out={};for(const lane of LANES){const idx=pool.findIndex(x=>x.ls.includes(lane));if(idx>=0){out[lane]=pool[idx].h.name;pool.splice(idx,1)}}for(const lane of LANES)if(!out[lane]&&pool.length)out[lane]=pool.shift().h.name;return out}
function teamStrength(side){const team=picks(side),ts=team.map(tags);let s=50;if(ts.some(t=>t.has('frontline')))s+=8;if(ts.some(t=>t.has('engage')))s+=7;if(ts.some(t=>t.has('peel')))s+=5;if(ts.some(t=>t.has('magic')))s+=5;if(ts.some(t=>t.has('marksman')))s+=5;if(ts.some(t=>t.has('objective')))s+=5;s+=team.reduce((a,h)=>a+(metaEvidence(h).score-50)*.04,0);return s}
function renderComplete(){const root=document.getElementById('completeReport');if(!state.started||state.actions.length<steps().length){root.innerHTML='';return}const ba=assignRoles('Blue'),ra=assignRoles('Red'),bs=teamStrength('Blue'),rs=teamStrength('Red');let bp=clamp(Math.round(bs/(bs+rs)*100));bp=Math.max(35,Math.min(65,bp));const rp=100-bp;root.innerHTML=`<div class="complete-report"><h2>Professional Draft Review</h2><div class="advbar"><div class="blue" style="width:${bp}%"></div><div class="red" style="width:${rp}%"></div></div><div class="mode-note">Draft advantage estimate: Blue ${bp}% • Red ${rp}%. This is analytical inference, not a prediction of the match winner.</div><div class="matchups">${LANES.map(l=>`<div><b>${l}</b><br>Blue: ${esc(ba[l]||'Unresolved')}<br>Red: ${esc(ra[l]||'Unresolved')}</div>`).join('')}</div></div>`}
function renderAll(){renderMode();renderRoleTabs();renderBans();renderPicks();renderHeader();renderHeroGrid();renderRecommendations();renderIntel();renderMeta();renderDirectory();renderSources();renderComplete();persist()}

function handleHeroClick(name){if(isRankedBanSetup()){toggleRankedBan(name);return}const step=currentStep();if(!state.started)return toast('Choose a side and start the draft');if(!step)return;if(!isUserTurn(step))return toast('Wait for the AI coach');if(usedNames().has(name))return;state.actions.push({...step,hero:name,controlledBy:'user'});renderAll();toast(`You ${step.type} ${name}`);scheduleAI()}
function toggleRankedBan(name){const idx=state.rankedBans.indexOf(name);if(idx>=0){state.rankedBans.splice(idx,1);renderAll();return}if(state.rankedBans.length>=state.rankedBanTarget)return toast(`Maximum ${state.rankedBanTarget} bans selected`);state.rankedBans.push(name);renderAll();if(state.rankedBans.length===state.rankedBanTarget)toast('Ban pool complete. Choose a side or press Start Draft.')}
function aiAction(){const step=currentStep();if(!step||!isAITurn(step))return;const top=topRecommendations(1)[0];if(!top)return;state.actions.push({...step,hero:top.hero.name,controlledBy:'ai'});renderAll();toast(`AI ${step.side} ${step.type}: ${top.hero.name}`);scheduleAI()}
function scheduleAI(){clearTimeout(aiTimer);if(isAITurn(currentStep()))aiTimer=setTimeout(aiAction,700)}
function startDraft(){if(!state.userSide){openSideModal();return}if(state.mode==='ranked'&&state.rankedBans.length!==state.rankedBanTarget){toast(`Select exactly ${state.rankedBanTarget} banned heroes first`);return}state.started=true;state.actions=[];renderAll();toast(`${state.mode==='ranked'?'Ranked':'Tournament'} mock draft started`);scheduleAI()}
function resetDraft(){clearTimeout(aiTimer);state.started=false;state.actions=[];state.rankedBans=[];renderAll();toast('Draft reset')}
function undo(){clearTimeout(aiTimer);if(isRankedBanSetup()&&state.rankedBans.length){state.rankedBans.pop();renderAll();return}if(!state.actions.length)return;state.actions.pop();if(state.userSide!=='Spectator'){while(state.actions.length&&state.actions[state.actions.length-1].controlledBy==='ai')state.actions.pop()}renderAll()}
function switchMode(mode){if(mode===state.mode)return;clearTimeout(aiTimer);state.mode=mode;state.started=false;state.actions=[];state.rankedBans=[];renderAll();toast(mode==='ranked'?'Ranked mode: select 5–10 bans first':'Tournament mode: 6 total bans (2+2 first phase, 1+1 second phase)')}

function openSideModal(){document.getElementById('sideModal').classList.add('show');document.querySelectorAll('.side-choice').forEach(b=>b.classList.toggle('selected',b.dataset.side===state.sideDraft))}
function closeSideModal(){document.getElementById('sideModal').classList.remove('show')}
function openHeroDrawer(hero){const a=coachAnalysis(hero,pseudoStep()),alts=topRecommendations(4).filter(x=>x.hero.name!==hero.name).slice(0,3).map(x=>x.hero.name);document.getElementById('drawerBody').innerHTML=`<div class="drawer-hero"><div class="drawer-face">${heroImg(hero)}</div><div class="drawer-title"><h2>${esc(hero.name)}</h2><span>${esc(cardRole(hero))} • ${esc(lanes(hero).join(' / ')||'role unresolved')}</span></div></div><div class="analysis-grid"><div class="analysis-box"><b>DRAFT PRIORITY</b><span>${a.score}/100 • ${esc(a.type)}</span></div><div class="analysis-box"><b>RECENT META</b><span>${a.meta.score}/100 • ${esc(a.meta.confidence)} confidence<br>${esc(a.meta.detail)}</span></div><div class="analysis-box"><b>COUNTER VALUE</b><span>${a.counter}/100<br>Good into: ${esc(a.good.join(', ')||'No current enemy target')}</span></div><div class="analysis-box"><b>THREATS</b><span>${esc(a.threats.join(', ')||'No major threat identified yet')}</span></div><div class="analysis-box"><b>ALLY SYNERGY</b><span>${a.syn}/100<br>${esc(a.allies.join(', ')||'No strong ally pairing yet')}</span></div><div class="analysis-box"><b>ROLE / COMPOSITION</b><span>Role fit ${a.role}/100 • Composition ${a.comp}/100 • Flex ${a.flex}/100</span></div><div class="analysis-box"><b>DENIAL VALUE</b><span>${a.denial}/100</span></div><div class="analysis-box"><b>ALTERNATIVES</b><span>${esc(alts.join(', ')||'None')}</span></div></div>`;document.getElementById('heroDrawer').classList.add('show')}

async function loadHeroes(){let feed=[];try{const r=await fetch(HERO_FEED,{cache:'force-cache'});if(r.ok){const d=await r.json();feed=Array.isArray(d)?d:(d.heroes||d.data||[])}}catch{}heroes=mergeFeed(feed);renderAll()}

restore();
for(let n=5;n<=10;n++){const o=document.createElement('option');o.value=n;o.textContent=n;document.getElementById('rankedBanTarget').appendChild(o)}
document.getElementById('rankedBanTarget').value=state.rankedBanTarget;
document.getElementById('rankedBanTarget').onchange=e=>{state.rankedBanTarget=Number(e.target.value);if(state.rankedBans.length>state.rankedBanTarget)state.rankedBans=state.rankedBans.slice(0,state.rankedBanTarget);renderAll()};
document.getElementById('scopeSelect').value=state.scope;document.getElementById('scopeSelect').onchange=e=>{state.scope=e.target.value;renderAll()};
document.getElementById('searchInput').oninput=e=>{state.search=e.target.value;renderHeroGrid()};
document.querySelectorAll('.mode-tab').forEach(b=>b.onclick=()=>switchMode(b.dataset.mode));
document.getElementById('chooseSideBtn').onclick=openSideModal;document.getElementById('startBtn').onclick=startDraft;document.getElementById('undoBtn').onclick=undo;document.getElementById('resetBtn').onclick=resetDraft;document.getElementById('clearRankedBans').onclick=()=>{state.rankedBans=[];renderAll()};
document.querySelectorAll('.side-choice').forEach(b=>b.onclick=()=>{state.sideDraft=b.dataset.side;document.querySelectorAll('.side-choice').forEach(x=>x.classList.toggle('selected',x===b))});
document.getElementById('cancelSide').onclick=closeSideModal;document.getElementById('confirmSide').onclick=()=>{state.userSide=state.sideDraft;closeSideModal();renderAll();if(state.mode==='tournament')startDraft();else toast(`You are ${state.userSide}. Select ${state.rankedBanTarget} ranked bans.`)};
document.getElementById('closeDrawer').onclick=()=>document.getElementById('heroDrawer').classList.remove('show');document.getElementById('heroDrawer').onclick=e=>{if(e.target.id==='heroDrawer')e.currentTarget.classList.remove('show')};
document.querySelectorAll('.navbtn').forEach(b=>b.onclick=()=>{document.querySelectorAll('.navbtn').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById(b.dataset.page).classList.add('active');window.scrollTo({top:0,behavior:'smooth'})});
loadHeroes();renderAll();if(!state.userSide)setTimeout(openSideModal,250);else if(state.started)setTimeout(scheduleAI,500);