window.MLBB_ROSTER={
  updated:'2026-10-01',
  names:["Aamon","Akai","Aldous","Alice","Alpha","Alucard","Angela","Argus","Arlott","Atlas","Aulus","Aurora","Badang","Balmond","Bane","Barats","Baxia","Beatrix","Belerick","Benedetta","Brody","Bruno","Carmilla","Cecilion","Chang'e","Chip","Chou","Cici","Claude","Clint","Cyclops","Diggie","Dyrroth","Edith","Esmeralda","Estes","Eudora","Fanny","Faramis","Floryn","Franco","Fredrinn","Freya","Gatotkaca","Gloo","Gord","Granger","Grock","Guinevere","Gusion","Hanabi","Hanzo","Harith","Harley","Hayabusa","Helcurt","Hilda","Hirara","Hylos","Irithel","Ixia","Jawhead","Johnson","Joy","Julian","Kadita","Kagura","Kaja","Kalea","Karina","Karrie","Khaleed","Khufra","Kimmy","Lancelot","Lapu-Lapu","Layla","Leomord","Lesley","Ling","Lolita","Lukas","Lunox","Luo Yi","Lylia","Marcel","Martis","Masha","Mathilda","Melissa","Minotaur","Minsitthar","Miya","Moskov","Nana","Natalia","Natan","Nolan","Novaria","Obsidia","Odette","Paquito","Pharsa","Phoveus","Popol and Kupa","Rafaela","Roger","Ruby","Saber","Selena","Silvanna","Sora","Sun","Suyou","Terizla","Thamuz","Tigreal","Uranus","Vale","Valentina","Valir","Vexana","Wanwan","X.Borg","Xavier","Yi Sun-shin","Yin","Yu Zhong","Yve","Zetian","Zhask","Zhuxin","Zilong"],
  lanes:{
    EXP:["Aldous","Alice","Argus","Arlott","Benedetta","Chou","Cici","Dyrroth","Edith","Esmeralda","Freya","Gatotkaca","Gloo","Guinevere","Hilda","Khaleed","Lapu-Lapu","Lukas","Masha","Minsitthar","Paquito","Phoveus","Ruby","Silvanna","Sora","Sun","Suyou","Terizla","Thamuz","Uranus","X.Borg","Yu Zhong","Zilong"],
    JUNGLE:["Aamon","Akai","Alpha","Alucard","Aulus","Balmond","Bane","Barats","Baxia","Fanny","Fredrinn","Gusion","Hanzo","Harley","Hayabusa","Helcurt","Hirara","Joy","Julian","Karina","Lancelot","Leomord","Ling","Martis","Natalia","Nolan","Roger","Saber","Suyou","Yi Sun-shin","Yin"],
    MID:["Alice","Aurora","Cecilion","Chang'e","Cyclops","Eudora","Faramis","Gord","Kadita","Kagura","Kimmy","Lunox","Luo Yi","Lylia","Nana","Novaria","Odette","Pharsa","Selena","Vale","Valentina","Valir","Vexana","Xavier","Yve","Zetian","Zhask","Zhuxin"],
    GOLD:["Beatrix","Brody","Bruno","Claude","Clint","Granger","Hanabi","Harith","Irithel","Ixia","Karrie","Kimmy","Layla","Lesley","Melissa","Miya","Moskov","Natan","Obsidia","Popol and Kupa","Wanwan"],
    ROAM:["Akai","Angela","Atlas","Badang","Belerick","Carmilla","Chip","Diggie","Edith","Estes","Floryn","Franco","Gatotkaca","Gloo","Grock","Hilda","Hylos","Jawhead","Johnson","Kaja","Kalea","Khaleed","Khufra","Lolita","Marcel","Mathilda","Minotaur","Rafaela","Ruby","Tigreal"]
  },
  roleOverrides:{Hirara:['Assassin'],Marcel:['Support'],Obsidia:['Marksman'],Sora:['Fighter','Assassin'],Zetian:['Mage'],Kalea:['Support','Fighter'],Lukas:['Fighter'],Chip:['Support','Tank'],Suyou:['Assassin','Fighter'],Cici:['Fighter'],Freya:['Fighter'],Atlas:['Tank'],Belerick:['Tank'],Uranus:['Tank','Fighter'],Gloo:['Tank','Fighter'],Barats:['Tank','Fighter'],Carmilla:['Support','Tank'],Minotaur:['Tank','Support'],Mathilda:['Support','Assassin'],Edith:['Tank','Marksman']}
};